# Generated by Django 4.2.3 on 2023-07-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='diffiaculty',
            new_name='difficulty',
        ),
    ]
