# Generated by Django 4.2.3 on 2023-08-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='user',
        ),
    ]
