# Generated by Django 4.2.3 on 2023-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_remove_problems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default='2023-08-05'),
            preserve_default=False,
        ),
    ]
