# Generated by Django 4.2.3 on 2023-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='edited_at',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
