# Generated by Django 4.2.3 on 2023-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
