# Generated by Django 4.2.3 on 2023-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolist_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='finish_at',
            field=models.DateField(null=True),
        ),
    ]
