# Generated by Django 4.2.3 on 2023-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todolist_finish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
